#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
INDEX="$ROOT/.context/index.yaml"

python3 - "$ROOT" "$INDEX" <<'PYEOF'
import sys
import re
from pathlib import Path
from datetime import date

root = Path(sys.argv[1])
index_path = Path(sys.argv[2])
context_dir = root / ".context"


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return None
    try:
        end = text.index("---\n", 4)
    except ValueError:
        return None
    fm_text = text[4:end]
    fm = {}
    for line in fm_text.splitlines():
        if ": " in line and not line.startswith(" "):
            k, _, v = line.partition(": ")
            fm[k.strip()] = v.strip().strip('"')
    fm["_raw"] = fm_text
    return fm


entries = []
missing = []

for md in sorted(context_dir.rglob("*.md")):
    rel = str(md.relative_to(root))
    content = md.read_text()
    fm = parse_frontmatter(content)
    if fm is None:
        missing.append(rel)
        continue
    required = ["title", "type", "status", "date"]
    absent = [f for f in required if not fm.get(f)]
    if absent:
        missing.append(f"{rel} (missing: {', '.join(absent)})")
        continue
    entry = {k: fm[k] for k in required}
    entry["path"] = rel
    related_match = re.search(r"related:\n((?:  - .+\n?)+)", fm["_raw"])
    if related_match:
        items = [
            ln.strip()[2:]
            for ln in related_match.group(1).splitlines()
            if ln.strip().startswith("- ")
        ]
        entry["related"] = items
    entries.append(entry)

if missing:
    print(
        "WARNING: files with missing frontmatter (excluded from index):", file=sys.stderr
    )
    for f in missing:
        print(f"  {f}", file=sys.stderr)

lines = [
    "# Auto-generated by context-index skill. Do not edit manually.",
    f"# Last updated: {date.today().isoformat()}",
    "entries:",
]
for e in entries:
    lines.append(f"  - path: {e['path']}")
    lines.append(f'    title: "{e["title"]}"')
    lines.append(f"    type: {e['type']}")
    lines.append(f"    status: {e['status']}")
    lines.append(f"    date: {e['date']}")
    if e.get("related"):
        lines.append("    related:")
        for r in e["related"]:
            lines.append(f"      - {r}")

index_path.write_text("\n".join(lines) + "\n")
print(f"Generated {len(entries)} entries -> {index_path}")
PYEOF
