#!/usr/bin/env bash
set -euo pipefail

CHECK_MODE=false
if [ "${1:-}" = "--check" ]; then
  CHECK_MODE=true
fi

ROOT="$(git rev-parse --show-toplevel)"
INDEX="$ROOT/.context/index.yaml"

python3 - "$ROOT" "$INDEX" "$CHECK_MODE" <<'PYEOF'
import sys
import re
from pathlib import Path
from datetime import date

root = Path(sys.argv[1])
index_path = Path(sys.argv[2])
check_mode = sys.argv[3] == "true"
context_dir = root / ".context"


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return None
    try:
        end = text.index("---\n", 4)
    except ValueError:
        return None
    fm_text = text[4:end]
    fm = {}
    for line in fm_text.splitlines():
        if ": " in line and not line.startswith(" "):
            k, _, v = line.partition(": ")
            fm[k.strip()] = v.strip().strip('"')
    fm["_raw"] = fm_text
    return fm


entries = []
missing = []
plugins_dir = context_dir / "plugins"

for md in sorted(context_dir.rglob("*.md")):
    if plugins_dir in md.parents:
        continue
    rel = str(md.relative_to(root))
    content = md.read_text()
    fm = parse_frontmatter(content)
    if fm is None:
        missing.append(rel)
        continue
    required = ["title", "type", "status", "date"]
    absent = [f for f in required if not fm.get(f)]
    if absent:
        missing.append(f"{rel} (missing: {', '.join(absent)})")
        continue
    entry = {k: fm[k] for k in required}
    entry["path"] = rel
    related_match = re.search(r"related:\n((?:  - .+\n?)+)", fm["_raw"])
    if related_match:
        items = [
            ln.strip()[2:]
            for ln in related_match.group(1).splitlines()
            if ln.strip().startswith("- ")
        ]
        entry["related"] = items
    entries.append(entry)

if missing:
    print(
        "WARNING: files with missing frontmatter (excluded from index):", file=sys.stderr
    )
    for f in missing:
        print(f"  {f}", file=sys.stderr)

type_group_key = {"plan": "plans", "finding": "findings", "analysis": "analysis", "instruction": "instructions", "audit": "audits"}
type_order = ["plans", "findings", "analysis", "audits", "instructions"]
type_label = {"plans": "Plans", "findings": "Findings", "analysis": "Analysis", "audits": "Audits", "instructions": "Instructions"}

grouped = {}
for e in entries:
    key = type_group_key.get(e["type"], "other")
    grouped.setdefault(key, []).append(e)
# fold unknown types into a catch-all
other = grouped.pop("other", [])
for t in list(grouped):
    if t not in type_order:
        other.extend(grouped.pop(t))
if other:
    grouped["other"] = other
    type_order.append("other")
    type_label["other"] = "Other"

# Count statuses for the summary
status_counts = {}
for e in entries:
    s = e["status"]
    status_counts[s] = status_counts.get(s, 0) + 1
status_summary = ", ".join(f"{n} {s}" for s, n in sorted(status_counts.items()))

lines = [
    "# Auto-generated by context-index skill. Do not edit manually.",
    f"# Last updated: {date.today().isoformat()}",
    f"# {len(entries)} entries: {status_summary}",
    "",
]
for t in type_order:
    lst = grouped.get(t)
    if not lst:
        continue
    lines.append(f"# ── {type_label[t]} ({len(lst)}) ──")
    lines.append(f"{t}:")
    for e in lst:
        lines.append(f'  - path: "{e["path"]}"')
        lines.append(f'    title: "{e["title"]}"')
        lines.append(f"    status: {e['status']}")
        lines.append(f"    date: {e['date']}")
        if e.get("related"):
            lines.append("    related:")
            for r in e["related"]:
                lines.append(f"      - {r}")
    lines.append("")

output = "\n".join(lines) + "\n"
if check_mode:
    current = index_path.read_text() if index_path.exists() else ""
    if output != current:
        print("ERROR: .context/index.yaml is stale — run 'hk fix' to regenerate", file=sys.stderr)
        sys.exit(1)
    print("context index is fresh")
else:
    index_path.write_text(output)
    print(f"Generated {len(entries)} entries -> {index_path}")
PYEOF
