package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pantheon-org/skill-quality-auditor/internal/patternconfig"
)

// writeMarkerConfig writes a structurally valid scoring-patterns.yaml whose
// d1_knowledge_delta.beginner_signals is exactly [marker], so tests can tell
// which tier's file ended up active.
func writeMarkerConfig(t *testing.T, path, marker string) {
	t.Helper()
	content := "version: 1\n" +
		"patterns:\n" +
		"  d1_knowledge_delta:\n" +
		"    beginner_signals: [\"" + marker + "\"]\n" +
		"    expert_signals: [\"x\"]\n" +
		"  analysis_quality:\n" +
		"    hedge_words: [\"x\"]\n" +
		"    vague_words: [\"x\"]\n" +
		"    passive_patterns: [\"x\"]\n" +
		"  d6_freedom_calibration:\n" +
		"    when_not_to_use: [\"x\"]\n"
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write marker config: %v", err)
	}
}

// activeMarker returns the current active config's single beginner signal,
// for comparing against the marker written by writeMarkerConfig.
func activeMarker(t *testing.T) string {
	t.Helper()
	signals := patternconfig.Get().Patterns.D1KnowledgeDelta.BeginnerSignals
	if len(signals) == 0 {
		t.Fatal("active config has no beginner signals")
	}
	return signals[0]
}

// withUserConfigDir points the default config-directory tier at dir for the
// duration of the test, restoring the TestMain-installed stub afterward.
func withUserConfigDir(t *testing.T, dir string) {
	t.Helper()
	orig := userConfigDir
	userConfigDir = func() (string, error) { return dir, nil }
	t.Cleanup(func() { userConfigDir = orig })
}

func TestResolveConfig_FlagWinsOverCWDAndDefault(t *testing.T) {
	resetConfigFlags(t)

	cwdDir := t.TempDir()
	t.Chdir(cwdDir)
	writeMarkerConfig(t, filepath.Join(cwdDir, userConfigFileName), "cwd-marker")

	defaultDir := t.TempDir()
	withUserConfigDir(t, defaultDir)
	writeMarkerConfig(t, filepath.Join(defaultDir, userConfigDirName, userConfigFileName), "default-marker")

	flagPath := filepath.Join(t.TempDir(), "flag-config.yaml")
	writeMarkerConfig(t, flagPath, "flag-marker")
	configFlag = flagPath
	t.Cleanup(func() { configFlag = "" })

	if err := resolveConfig(false); err != nil {
		t.Fatalf("resolveConfig: %v", err)
	}
	if got := activeMarker(t); got != "flag-marker" {
		t.Errorf("expected the -c flag to win, got %q", got)
	}
}

func TestResolveConfig_CWDWinsOverDefault_WhenFlagAbsent(t *testing.T) {
	resetConfigFlags(t)

	cwdDir := t.TempDir()
	t.Chdir(cwdDir)
	writeMarkerConfig(t, filepath.Join(cwdDir, userConfigFileName), "cwd-marker")

	defaultDir := t.TempDir()
	withUserConfigDir(t, defaultDir)
	writeMarkerConfig(t, filepath.Join(defaultDir, userConfigDirName, userConfigFileName), "default-marker")

	if err := resolveConfig(false); err != nil {
		t.Fatalf("resolveConfig: %v", err)
	}
	if got := activeMarker(t); got != "cwd-marker" {
		t.Errorf("expected the CWD file to win over the default path, got %q", got)
	}
}

func TestResolveConfig_DefaultPath_AutoGeneratedOnFirstRun_AndReusedOnSecondRun(t *testing.T) {
	resetConfigFlags(t)

	t.Chdir(t.TempDir()) // no CWD file
	defaultDir := t.TempDir()
	withUserConfigDir(t, defaultDir)
	generatedPath := filepath.Join(defaultDir, userConfigDirName, userConfigFileName)

	if _, err := os.Stat(generatedPath); !os.IsNotExist(err) {
		t.Fatalf("expected no file before first run, stat err: %v", err)
	}

	if err := resolveConfig(false); err != nil {
		t.Fatalf("resolveConfig (first run): %v", err)
	}
	firstInfo, err := os.Stat(generatedPath)
	if err != nil {
		t.Fatalf("expected auto-generated file after first run: %v", err)
	}
	if got := activeMarker(t); got != "npm install" {
		t.Errorf("expected embedded default active on first run, got %q", got)
	}

	if err := resolveConfig(false); err != nil {
		t.Fatalf("resolveConfig (second run): %v", err)
	}
	secondInfo, err := os.Stat(generatedPath)
	if err != nil {
		t.Fatalf("expected the generated file to persist: %v", err)
	}
	if !firstInfo.ModTime().Equal(secondInfo.ModTime()) {
		t.Error("expected the second run to reuse the generated file as-is, not rewrite it")
	}
	if got := activeMarker(t); got != "npm install" {
		t.Errorf("expected embedded default active on second run, got %q", got)
	}
}

func TestResolveConfig_NoUserConfig_SkipsAllTiersAndNeverWrites(t *testing.T) {
	resetConfigFlags(t)

	cwdDir := t.TempDir()
	t.Chdir(cwdDir)
	writeMarkerConfig(t, filepath.Join(cwdDir, userConfigFileName), "cwd-marker")

	defaultDir := t.TempDir()
	withUserConfigDir(t, defaultDir)

	flagPath := filepath.Join(t.TempDir(), "flag-config.yaml")
	writeMarkerConfig(t, flagPath, "flag-marker")
	configFlag = flagPath
	noUserConfigFlag = true
	t.Cleanup(func() { configFlag = ""; noUserConfigFlag = false })

	if err := resolveConfig(false); err != nil {
		t.Fatalf("resolveConfig: %v", err)
	}
	if got := activeMarker(t); got != "npm install" {
		t.Errorf("expected embedded default with --no-user-config, got %q", got)
	}
	if _, err := os.Stat(filepath.Join(defaultDir, userConfigDirName, userConfigFileName)); !os.IsNotExist(err) {
		t.Errorf("expected --no-user-config to suppress auto-generation, stat err: %v", err)
	}
}

func TestResolveConfig_Eval_IgnoresAllUserSourcesEvenWhenPresent(t *testing.T) {
	resetConfigFlags(t)

	cwdDir := t.TempDir()
	t.Chdir(cwdDir)
	writeMarkerConfig(t, filepath.Join(cwdDir, userConfigFileName), "cwd-marker")

	defaultDir := t.TempDir()
	withUserConfigDir(t, defaultDir)
	writeMarkerConfig(t, filepath.Join(defaultDir, userConfigDirName, userConfigFileName), "default-marker")

	flagPath := filepath.Join(t.TempDir(), "flag-config.yaml")
	writeMarkerConfig(t, flagPath, "flag-marker")
	configFlag = flagPath
	t.Cleanup(func() { configFlag = "" })

	if err := resolveConfig(true); err != nil {
		t.Fatalf("resolveConfig: %v", err)
	}
	if got := activeMarker(t); got != "npm install" {
		t.Errorf("expected eval to always use the embedded config, got %q", got)
	}
}

func TestResolveConfig_EmbeddedUnchanged_WhenAutoGenerationFails(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("running as root: permission bits are not enforced")
	}
	resetConfigFlags(t)

	t.Chdir(t.TempDir()) // no CWD file
	readOnlyParent := t.TempDir()
	if err := os.Chmod(readOnlyParent, 0o500); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(readOnlyParent, 0o755) })
	withUserConfigDir(t, filepath.Join(readOnlyParent, "unwritable"))

	if err := resolveConfig(false); err != nil {
		t.Fatalf("resolveConfig should never fail even if auto-generation fails: %v", err)
	}
	if got := activeMarker(t); got != "npm install" {
		t.Errorf("expected embedded default despite write failure, got %q", got)
	}
}

func TestResolveConfig_ExplicitFlagMissingFile_HardError(t *testing.T) {
	resetConfigFlags(t)
	configFlag = filepath.Join(t.TempDir(), "does-not-exist.yaml")
	t.Cleanup(func() { configFlag = "" })

	err := resolveConfig(false)
	if err == nil {
		t.Fatal("expected a hard error for a missing --config file")
	}
	if !strings.Contains(err.Error(), "--config") {
		t.Errorf("expected error to reference --config, got %v", err)
	}
}

func TestResolveConfig_ExplicitFlagMalformedFile_HardError(t *testing.T) {
	resetConfigFlags(t)
	path := filepath.Join(t.TempDir(), "malformed.yaml")
	if err := os.WriteFile(path, []byte("not: [valid"), 0o644); err != nil {
		t.Fatalf("write malformed fixture: %v", err)
	}
	configFlag = path
	t.Cleanup(func() { configFlag = "" })

	if err := resolveConfig(false); err == nil {
		t.Fatal("expected a hard error for a malformed --config file")
	}
}

// TestConfigFlag_WiredThroughRealCLIParsing exercises the actual cobra flag
// declaration and PersistentPreRunE hook end to end (as opposed to calling
// resolveConfig directly), confirming "-c" placed before the subcommand, as
// documented, actually reaches resolveConfig via the real argv parse path.
func TestConfigFlag_WiredThroughRealCLIParsing(t *testing.T) {
	resetConfigFlags(t)
	root, key := makeEvalSkill(t, "skill-minimal", "domain", "cli-flag-skill")

	t.Chdir(t.TempDir())
	withUserConfigDir(t, t.TempDir())

	flagPath := filepath.Join(t.TempDir(), "flag-config.yaml")
	writeMarkerConfig(t, flagPath, "cli-flag-marker")

	rootCmd.SetOut(&strings.Builder{})
	rootCmd.SetErr(&strings.Builder{})
	rootCmd.SetArgs([]string{"-c", flagPath, "evaluate", "--repo-root", root, key})
	defer rootCmd.SetArgs(nil)

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("execute: %v", err)
	}
	if got := activeMarker(t); got != "cli-flag-marker" {
		t.Errorf("expected -c placed before the subcommand to reach resolveConfig, got %q", got)
	}
}
